spring.application.name=project-pipeline
server.port=8045
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pipeline}
spring.datasource.username=${DB_USERNAME:pipeline}
spring.datasource.password=${DB_PASSWORD:pipeline}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
